### ISSUE TITLE
If public key contains a space, errors are generated.

### ISSUE THREAD

**Issue by zyphlar** [YunoHost-Apps/borgserver_ynh#12]
My borg client is not via yunohost, so I assumed that "public key" would take the form of `ssh-rsa RANDOMKEYTEXT myuser@myhost` however this caused major errors with my server (I even had to reboot.) Additionally it's not obvious where this info gets stored (only looking through these issues did I realize it can be found in `/home/my_ssh_user/.ssh/authorized_keys`) so fixing the problem afterwards was unclear. (I uninstalled a few times before finally getting it right.)

**Comment by zamentur** [comment]
Fixed https://github.com/YunoHost-Apps/borgserver_ynh/pull/24
