### ISSUE TITLE
Bad things can happen if admin choose an existing ssh user

### ISSUE THREAD

**Issue by autra** [YunoHost-Apps/borgserver_ynh#14]
# Description 

If someone installs this app and choose an existing user as ssh user, it will attempt a userdel on remove (either by removing this app manually, or because the installation fails).

I propose to:
- document the fact that we need a new user.
- abort the installation with an error message if the user already exists.

WDYT?

**Comment by autra** [comment]
Actually I realised that the script did fail if the user already exists. But then the remove script is executed to cleanup, which tries to userdel.

In this case, we want to cleanup, but avoid the userdel command *if* the reason we are cleaning up is because the user wasn't correctly chosen. Not sure how to achieve that tough.

**Comment by zamentur** [comment]
Thanks for reporting this 
Fixed with https://github.com/YunoHost-Apps/borgserver_ynh/pull/22

**Comment by zamentur** [comment]
Thanks for reporting this, it's fixed with https://github.com/YunoHost-Apps/borgserver_ynh/pull/24
