### ISSUE TITLE
Some files are not cleaned up when removing this app

### ISSUE THREAD

**Issue by autra** [YunoHost-Apps/borgserver_ynh#18]
List of files not cleaned up
- /opt/borg-env
- /etc/yunohost/hooks.d/backup/17-data_home

**Comment by autra** [comment]
- /usr/local/bin/borg

**Comment by zamentur** [comment]
About /etc/yunohost/hooks.d/backup/17-data_home it's now fixed. 
About the 2 others it's quite difficult to delete it because some person use the app twice or more, and it's a shared directory.

So i close this ticket

**Comment by autra** [comment]
I see. I think it's still possible to know if there is still a borgserver_ynh installed. Does it make sense to use it more than once though?

**Comment by zamentur** [comment]
> Does it make sense to use it more than once though?

Personnaly i have install it several times on same machine to backup separately several team servers

If you have 2 firens to backup, they wont share the same public key... It could be improve if we create a config panel to manage a list of backup account.
