### ISSUE TITLE
Rights problems on the borg executable

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/borgserver_ynh#27]
`/usr/local/bin/borg` has a right of 740
Borg user is not in staff group

```
~ ls -l /usr/local/bin/borg
-rwxr--r-- 1 root staff 69 avril 27 11:28 /usr/local/bin/borg
~ sudo groups borguser
borguser : borguser
```

For the backup to work, I changed the rights to add exec right for group and added borguser to the staff group.

**Comment by roukydesbois** [comment]
I had the same issue - although I more brutally did a chmod +x just in case

**Comment by KvL159** [comment]
This issue is still there, while using borg command, it'll return an error, permissions and user/group need to be changed

**Comment by zamentur** [comment]
Fixed in testing https://github.com/YunoHost-Apps/borgserver_ynh/blob/testing/scripts/_common.sh#L26
